### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amnotbananaama** [Ashley1227/rich-chat#1]
Hi, thank you for creating this mod! I was hoping to try it out on my server, but ran into a couple of issues. 

1) Rich Chat appears to have been [removed](https://www.curseforge.com/minecraft/mc-mods/rich-chat) from CurseForge. Was this intentional, and if so do you still plan on supporting the mod? I totally understand if not.

2) Do you have any plans to update the mod to future versions of Minecraft? It currently crashes on Minecraft 1.16.3 with the following error (after removing the hardlocked version requirement):

### Crash Log
[latest.log](https://gist.github.com/amnotbananaama/9097d6b6ea10b4e5b22c34e458eefff5)

Thanks for taking the time to read this!

**Comment by Ashley1227** [comment]
Oh, what? Didn't know it was removed. Sorry, I haven't been active on GH lately. I'll go check out what happened to it I guess

**Comment by amnotbananaama** [comment]
Closing, as I just noticed the mod has been updated to support 1.16.3. Posting on CF is certainly not required, but a formal release would be awesome so users don't have to build from source. Thanks for looking into this, I appreciate it and I'm very excited to try out the mod
